---
title: "Data Simulation Examples"
author: "Gustavo Garcia-Franceschini"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nph)
```

```{r}
# 0 = control; 1 = treat
treat = factor(sample(c(0,1), size = 1000, replace = T))

treated = sum(treat == "1")

#time: 28 days
#t = sample(28:365, size = 1000, replace = T)

# t is weibull distributed

random_num = runif(n = 1000)
```

# Proportional

For this one, we'll just sample from two different Weibull distributions.

```{r}
proportional = tibble(
  
  treat = treat,
  
  #t = t,
  
  weibull_var = case_when(
    
    treat == "1" ~ rweibull(1000, shape = 10^-1, scale = 5),
    
    treat == "0" ~ rweibull(1000, shape = 7^-1, scale= 5),
    
  ),
  
  weibull_p = case_when(
    
    treat == "1" ~ pweibull(weibull_var, shape = 10^-1, scale = 5),
    
    treat == "0" ~ pweibull(weibull_var, shape = 7^-1, scale= 5),
    
  ),
  
  t = weibull_p*28,
  
  #From documentation. Gets cumulative hazard
  cum_hazard = case_when(
    
    treat == "1" ~ -pweibull(t, shape = 10^-1,
                           lower = FALSE, log = TRUE),
    
    treat == "0" ~ -pweibull(t, shape = 7^-1,
                           lower = FALSE, log = TRUE),
    
  ),
  
  #We use cumulative hazard to find S(t), probability that individual i
  #is alive after t
  
  survival_prob = exp(-cum_hazard),
  
  #Give me a random random between 0 and 1
  random_num = random_num,
  
  #If survival_prob is greater than random number, the person died
  #else, the person is alive
  #Survival prob: indicates the probability that the event of interest
  #has not yet occurred by time t
  
  dead = if_else(survival_prob >= random_num, F, T)
)

```

```{r}
table(proportional$treat, proportional$dead)
```

```{r}
ggplot(proportional) +
  geom_line(aes(x = t, y = survival_prob, col = treat))
```


```{r}
logrank.test(proportional$t, proportional$dead, proportional$treat, 
             rho = 0, gamma = 0 )
```

```{r}
plot(survival::survfit(survival::Surv(t, dead) ~ treat, data = proportional))
```



